### ISSUE TITLE
Option to filter by whole words (not fuzzy)

### ISSUE THREAD

**Issue by Justinzobel** [charmbracelet/gum#50] opened 2022-07-31 04:56 UTC
For instance

echo "The quick brown fox" | gum filter

Will show up if I type `hioo` in the filter.

I'd prefer an option where it will only show up `quick` or `k bro`

**Comment by FiReLScar** [comment] 2022-07-31 10:41
Are you saying that it searches the entire string for those characters instead of a singular word?

**Comment by Justinzobel** [comment] 2022-07-31 13:03
Yeah it will highlight each letter.

![image](https://user-images.githubusercontent.com/1370117/182027774-9e289621-70b9-4be7-be52-830292d7a268.png)

**Comment by FiReLScar** [comment] 2022-08-01 09:10
I just found this project but they use [sahilm/fuzzy](https://github.com/sahilm/fuzzy) for the fuzzy searching so maybe the problem is with them. Again I just found this project so I could be wrong.

**Comment by mathomp4** [comment] 2022-08-09 20:17
Agreed this would be useful. In my testing with `gum filter` I have say:
```
> Filter...
• Clear
  /Users/mathomp4/Models/GrITAS-MERRA2_V2_SLES12-fromCVS/GrITAS
  /Users/mathomp4/Models/mat-qvi-1_0_r3-SLES12-fromCVS/QVI
  /Users/mathomp4/Models/GEOSgcm-GNU-TestMOM6AppUpdate/GEOSgcm
  /Users/mathomp4/Models/GEOSgcm-Intel-TestMOM6AppUpdate/GEOSgcm
  /Users/mathomp4/Models/GEOSldas-NAG-OLD/GEOSldas
  /Users/mathomp4/Models/GEOSldas-NAG/GEOSldas
  /Users/mathomp4/Models/GrITAS-MERRA2_V2_SLES12-fromCVS/GrITAS
  /Users/mathomp4/Models/mat-qvi-1_0_r3-SLES12-fromCVS/QVI
  /Users/mathomp4/Models/MAPL3-GNU/MAPL
  /Users/mathomp4/Models/MAPL-GNU12-ZstdBaselib/MAPL
  /Users/mathomp4/Models/MAPL-GNU/MAPL
  /Users/mathomp4/Models/MAPL-Intel/MAPL
  /Users/mathomp4/Models/MAPL-NAG-7.1_7113/MAPL
  /Users/mathomp4/Models/MAPL-mepopackage/MAPL
```
and I'd like to drill down to the `MAPL` ones. Unfortunately, when I try that I get pretty much everything still there since all it matches letters early on that don't "mean" as much:

<img width="531" alt="Screen Shot 2022-08-09 at 4 16 02 PM" src="https://user-images.githubusercontent.com/2982494/183752322-80a08e6d-24aa-45e7-93b7-cbccd351f5e1.png">

Note that filtering on `mapl` or `MAPL` doesn't help.

**Comment by mathomp4** [comment] 2022-08-29 19:45
> I just found this project but they use [sahilm/fuzzy](https://github.com/sahilm/fuzzy) for the fuzzy searching so maybe the problem is with them. Again I just found this project so I could be wrong.

It looks like @isacikgoz has made some improvements on the original fuzzy. Maybe he'd know if whole-word searching is possible?

**Comment by enrichman** [comment] 2022-10-08 21:17
Since I like this project and it's part of the Hacktoberfest I was trying to have a look at this.

I have a working POC, can I assign this to me and open a PR?

**Comment by maaslalani** [comment] 2022-10-08 21:18
Hey @enrichman for sure you can open a PR!

**Comment by enrichman** [comment] 2022-10-08 22:39
Thanks @maaslalani, I've found a couple of issues with my initial approach, but I've fixed them.

**Closed** 2022-10-13 14:58 UTC
Labels: enhancement
