### ISSUE TITLE
Can't add apt repo on ubuntu 22:04

### ISSUE THREAD

**Issue by mcueto** [charmbracelet/gum#73] opened 2022-08-01 22:43 UTC
**Describe the bug**
Hi guys, i was trying to add `gum` to an `ubuntu:22.04` Dockerfile and have problems adding the repo to the list, so i was wondering if the `apt` repository is working at all(?).

``` Dockerfile
FROM ubuntu:22.04

RUN apt update
RUN apt install -y software-properties-common

RUN add-apt-repository -y https://repo.charm.sh/apt/
RUN apt update
RUN apt install -y gum
```

**To Reproduce**
1. Add the code above inside a Dockerfile that uses  `docker:22.04` as the base image
2. Build the image
3. See 404 not found error

**Expected behavior**
Should be able of installing `gum` using the `apt` repo as a source.

**Screenshots**
![image](https://user-images.githubusercontent.com/16097410/182257434-dc7c83da-ee7e-494b-853a-4f8f99ac7b2b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Doesn't apply
 - Version: 22.04

**Comment by caarlos0** [comment] 2022-08-02 13:29
can confirm, and doing:

```
RUN echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | tee /etc/apt/sources.list.d/charm.list
RUN apt update
RUN apt install -y gum
```

I get certificate errors instead.

@aymanbagabas I don't have access to the gpg bit in gemfury's config, could you take a look?

**Comment by caarlos0** [comment] 2022-08-02 13:32
ahh, just remembered, need to install ca-certificates too.

@mcueto this works:

```dockerfile
FROM ubuntu:22.04

RUN apt update
RUN apt install ca-certificates -y

RUN echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | tee /etc/apt/sources.list.d/charm.list
RUN apt update
[
RUN apt install -y gum
```

**Comment by caarlos0** [comment] 2022-08-02 13:39
so, not a bug. closing

**Closed by caarlos0** 2022-08-02 13:39 UTC

**Comment by mcueto** [comment] 2022-08-02 13:51
Thanks for the response, it can be used like you pointed out, thanks!
