### ISSUE TITLE
Allow multiple selection in `gum file`

### ISSUE THREAD

**Issue by simjnd** [charmbracelet/gum#199] opened 2022-10-12 19:14 UTC
**Is your feature request related to a problem? Please describe.**
Use `gum file`. Try to select multiple files or folders.

**Describe the solution you'd like**
Add a `--limit` and `--no-limit` option to `gum file` to allow selecting several files and folders, similar to `gum choose` and `gum filter`.

**Describe alternatives you've considered**
You could either chain `gum file` calls but then it wouldn't show you all your selected files at once, and it would always reset your position (folder, scroll position). 

**Additional context**
N/A

**Comment by BlueFalconHD** [comment] 2022-10-12 19:23
duplicate of #197

**Comment by maaslalani** [comment] 2022-12-13 19:55
Thanks for opening this issue @simjnd. We'll move this discussion to #197

**Closed by maaslalani** 2022-12-13 19:55 UTC
Labels: enhancement
