### ISSUE TITLE
pre-select defaults with gum choose

### ISSUE THREAD

**Issue by artis3n** [charmbracelet/gum#131] opened 2022-08-26 16:49 UTC
**Is your feature request related to a problem? Please describe.**

When providing a list of items with `gum choose --no-limit` , I'd like to pre-select several of the options to indicate these are the intended defaults, but all chosen items could be customized by the end user.

**Describe the solution you'd like**

Some kind of command like:

```bash
gum choose --no-limit --default 1,2 "First Thing" "Second Thing" "Third Thing"
```

results in the `gum choose` equivalent of:

- [x] First Thing
- [x] Second Thing
- [ ] Third Thing

with the rest of `gum choose`'s behavior remaining the same (user can un-select the pre-selected defaults, select other options, etc.).

**Describe alternatives you've considered**

`echo` out the intended defaults and prompt the user to confirm if they move forward without selecting the intended defaults. The suggested solution would make more a better user experience.

**Additional context**

**Comment by vanielf** [comment] 2022-09-06 18:37
seems duplicated from #72

**Comment by maaslalani** [comment] 2022-09-06 18:39
Closing because duplicate of #72 as @vanielf mentioned

**Closed by maaslalani** 2022-09-06 18:39 UTC

**Comment by artis3n** [comment] 2022-09-06 18:45
Good catch! Missed that earlier issue
