### ISSUE TITLE
gum choose wrapping (intended?)

### ISSUE THREAD

**Issue by NQMVD** [charmbracelet/gum#556] opened 2024-05-01 13:41 UTC
**Describe the bug**
Cursor doesn't wrap back to the top when hitting the bottom and pressing 'j' (same with top and pressing 'k').

**Expected behavior**
When hitting the bottom of a list with `gum choose` you were able to jump back to the top with pressing down again.
Maybe make it an option if this is intended.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by ptrcnull** [comment] 2024-05-01 16:29
seems like it's a regression in 0.14.0 after switching to [huh][1]

[1]: https://github.com/charmbracelet/huh

**Comment by hfhchan-plb** [comment] 2024-07-04 07:01
The reason why we switched from fzf to gum was that using arrow keys would wrap the selection around, and now it's gone...

Wrap around allows us to choose the last item in the list by pressing up when on the first item, now I need to hold the down button for multiple deciseconds...

**Comment by caarlos0** [comment] 2024-07-24 18:59
will be fixed by https://github.com/charmbracelet/huh/pull/324

**Closed** 2024-12-04 13:50 UTC
Labels: bug, cmd/choose
