### ISSUE TITLE
using spin with cycles

### ISSUE THREAD

**Issue by fragolinux** [charmbracelet/gum#336] opened 2023-04-08 21:03 UTC
hi, i've tihs code and i'd like to put it in some "spin" command, so the user knows something is going on in background... tried to put it in a function, same result, spin accepts only commands or scripts, not pieces of code or function, as it seems... hints? thanks

```
for profile in "${!profiles[@]}"; do
    PROFILE="$profile" ENABLED="${profiles[$profile]}" yq -i '.data.profiles.[env(PROFILE)].enabled |= env(ENABLED)' "$XDG_CONFIG_HOME/chezmoi/chezmoi.yaml"
done
```

**Comment by piero-vic** [comment] 2024-09-15 17:14
This might work https://github.com/charmbracelet/gum/issues/419#issuecomment-2351679739

**Comment by caarlos0** [comment] 2024-11-18 16:29
duplicate of #419

**Closed** 2024-11-18 17:00 UTC
