### ISSUE TITLE
Enter does not select an item with `gum choose --no-limit`

### ISSUE THREAD

**Issue by basilioss** [charmbracelet/gum#354] opened 2023-05-11 08:51 UTC
**Describe the bug**
Currently, to select one item with `gum choose --no-limit` you first need to explicitly mark it as selected with Tab/x/Ctrl+Space, but it would be easier to be able to just press Enter. Although, Enter works if there is only one item to select.

**To Reproduce**
1. Run `echo "one\ntwo\nthree" | gum choose --no-limit`
2. Try to choose something with Enter key without Tab/x etc.

**Expected behavior**
User should be able to select one item with Enter.

**Screenshots**

![out](https://github.com/charmbracelet/gum/assets/71596800/a04e7125-b146-4d7a-944a-e8ede010a5c8)

Here's also vhs tape to better understand what's going on:

```
Type 'echo -e "one\ntwo\nthree" | gum choose --no-limit'
Enter
Sleep 2000ms
Down
Sleep 2000ms
Enter
Sleep 2000ms
Type 'echo -e "one\ntwo\nthree" | gum choose'
Enter
Sleep 2000ms
Down
Sleep 2000ms
Enter
Sleep 2000ms
Type 'echo "one" | gum choose --no-limit'
Enter
Sleep 2000ms
Enter
Sleep 4000ms
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.10.0 (0f0f8e9)

**Additional context**
Seems like it worked in version 0.9.0

**Comment by MikaelFangel** [comment] 2023-05-13 21:32
Duplicate of #339

**Closed** 2023-05-13 21:51 UTC
